sudo: required

group: edge

services:
  - docker

install:
  - docker build --tag bodsch/docker-dashing-icinga2 .
  - docker run --detach --name dashing-icinga2 bodsch/docker-dashing-icinga2

script:
  - docker ps | grep -q dashing-icinga2

