sudo: required

group: edge

services:
  - docker

env:
  global:
    - BUILD_DATE=$(date +"%Y-%m-%d")
    - BUILD_VERSION=$(date +"%y%m")

jobs:
  include:
    - stage: build
      script:
        - make

    - stage: build and test
      script:
        - make
        - make start
        - make test
        - make stop

    - stage: build and push docker image
      script:
        - make
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        #
        - docker tag  ${USER}/dashing-icinga2:latest ${DOCKER_USERNAME}/docker-dashing-icinga2:latest
        - docker push ${DOCKER_USERNAME}/docker-dashing-icinga2:latest
        #
        - docker tag  ${DOCKER_USERNAME}/docker-dashing-icinga2:latest ${DOCKER_USERNAME}/docker-dashing-icinga2:${BUILD_VERSION}
        - docker push ${DOCKER_USERNAME}/docker-dashing-icinga2:${BUILD_VERSION}
        - docker logout
