---
version: '3.3'

services:

  # the Icinga2 Master
  # includes a certificate service to create and provide a icinga certificate
  icinga2-master:
    image: bodsch/docker-icinga2:1801-dev
    container_name: icinga2-master
    hostname: icinga2-master.matrix.lan
    restart: always
    ports:
      - 5665:5665
      - 8080
    environment:
      - ICINGA_API_USERS=root:icinga,dashing:dashing,cert:foo-bar
      - ICINGA_HOST=icinga2-master.matrix.lan
      - ICINGA_MASTER=icinga2-master.matrix.lan
      - BASIC_AUTH_USER=foofoo
      - BASIC_AUTH_PASS=barbar
      - ICINGA_CERT_SERVICE_BA_USER=admin
      - ICINGA_CERT_SERVICE_BA_PASSWORD=admin
      - ICINGA_CERT_SERVICE_API_USER=root
      - ICINGA_CERT_SERVICE_API_PASSWORD=icinga
      - ICINGA_CERT_SERVICE_SERVER=icinga2-master
      - ICINGA_CERT_SERVICE_PORT=8080
      - ICINGA_CERT_SERVICE_PATH=/
      - CARBON_HOST=
      - CARBON_PORT=2003
      - DEMO_DATA=true
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # the first icinga2 satellite
  # ask the master above for an certificate
  dashing-icinga2:
    build: .
    container_name: dashing-icinga2
    hostname: dashing-icinga2.matrix.lan
    restart: always
    ports:
      - 3030:3030
    environment:
      DEBUG: 'true'
      ICINGA_MASTER: icinga2-master.matrix.lan
      ICINGA_API_USER: root
      ICINGA_API_PASSWORD: icinga
      ICINGAWEB_URL: http://localhost/icinga
      ICINGA_CERT_SERVICE_BA_USER: foofoo
      ICINGA_CERT_SERVICE_BA_PASSWORD: barbar
      ICINGA_CERT_SERVICE_API_USER: dashing
      ICINGA_CERT_SERVICE_API_PASSWORD: dashing
      ICINGA_CERT_SERVICE_SERVER: icinga2-master.matrix.lan
      ICINGA_CERT_SERVICE_PORT: 8080
      ICINGA_CERT_SERVICE_PATH: /
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - icinga2-master:icinga2-master.matrix.lan
