# version: '2.0'

# the Icinga2 Master
# includes a certificate service to create and provide a icinga certificate
icinga2-master:
  image: bodsch/docker-icinga2:2.8.0-r2
  container_name: icinga2-master
  hostname: icinga2-master.matrix.lan
  ports:
    - 5665:5665
    - 4567:4567
  environment:
    - ICINGA_API_USERS=root:icinga,dashing:dashing,cert:foo-bar
    - ICINGA_MASTER=icinga2-master.matrix.lan
    - BASIC_AUTH_USER=foofoo
    - BASIC_AUTH_PASS=barbar
    - ICINGA_CLUSTER=true
    - ICINGA_CERT_SERVICE=true
    - ICINGA_CERT_SERVICE_BA_USER=admin
    - ICINGA_CERT_SERVICE_BA_PASSWORD=admin
    - ICINGA_CERT_SERVICE_API_USER=root
    - ICINGA_CERT_SERVICE_API_PASSWORD=icinga
    - ICINGA_CERT_SERVICE_SERVER=icinga2-master
    - ICINGA_CERT_SERVICE_PORT=4567
    - ICINGA_CERT_SERVICE_PATH=/
    - CARBON_HOST=
    - CARBON_PORT=2003
    - DEMO_DATA=false
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/docker-data/icinga2-master:/srv

# the first icinga2 satellite
# ask the master above for an certificate
dashing-icinga2:
  build: .
  container_name: dashing-icinga2
  hostname: dashing-icinga2.matrix.lan
  ports:
    - 3030:3030
  environment:
    DEBUG: 0
    ICINGA_HOST: icinga2-master.matrix.lan
    ICINGA_API_USER: root
    ICINGA_API_PASSWORD: icinga
    ICINGAWEB_URL: http://localhost/icinga
    ICINGA_CERT_SERVICE: true
    ICINGA_CERT_SERVICE_BA_USER: foofoo
    ICINGA_CERT_SERVICE_BA_PASSWORD: barbar
    ICINGA_CERT_SERVICE_API_USER: root
    ICINGA_CERT_SERVICE_API_PASSWORD: icinga
    ICINGA_CERT_SERVICE_SERVER: icinga2-master
    ICINGA_CERT_SERVICE_PORT: 4567
    ICINGA_CERT_SERVICE_PATH: /
    ICINGA_CERT_SERVICE: '{
        "ba": { "user":"foofoo", "password":"barbar" },
        "api": { "user":"dashing", "password":"dashing" },
        "server": "icinga2-master",
        "port": 4567,
        "path": "/"
      }'
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/docker-data/dashing-icinga2:/srv
  links:
    - icinga2-master:icinga2-master.matrix.lan
