# version: '2.0'


database:
  image: bodsch/docker-mysql:1707-27.1
  container_name: database
  hostname: database
  ports:
    - 3306:3306
  environment:
    - MYSQL_SYSTEM_USER=root
    - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/docker-data/database:/srv

# the Icinga2 Master
# includes a certificate service to create and provide a icinga certificate
icinga2-master:
  image: bodsch/docker-icinga2:1707-30.1
  container_name: icinga2-master
  hostname: icinga2-master.matrix.lan
  ports:
    - 5665:5665
    - 4567:4567
  environment:
    - DEBUG=1
    - ICINGA_API_USERS=root:icinga,dashing:dashing,cert:foo-bar
    - MYSQL_HOST=
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
    - ICINGA_MASTER=icinga2-master.matrix.lan
    - ICINGA_CLUSTER=true
    - ICINGA_CERT_SERVICE=true
    - ICINGA_CERT_SERVICE_BA_USER=admin
    - ICINGA_CERT_SERVICE_BA_PASSWORD=admin
    - ICINGA_CERT_SERVICE_API_USER=root
    - ICINGA_CERT_SERVICE_API_PASSWORD=icinga
    - ICINGA_CERT_SERVICE_SERVER=icinga2-master
    - ICINGA_CERT_SERVICE_PORT=4567
    - ICINGA_CERT_SERVICE_PATH=/
    - CARBON_HOST=
    - CARBON_PORT=2003
  volumes:
    - /tmp/docker-data/icinga2-master:/srv
  links:
    - database:database

# the first icinga2 satellite
# ask the master above for an certificate
smashing-icinga2:
  build: .
  container_name: smashing-icinga2
  hostname: smashing-icinga2.matrix.lan
  ports:
    - 3030:3030
  environment:
    - DEBUG=1
    - ICINGA_HOST=icinga2-master.matrix.lan
    - ICINGA_API_USER=root
    - ICINGA_API_PASSWORD=icinga
    - ICINGAWEB_URL=http://localhost/icinga
    - ICINGA_CERT_SERVICE=true
    - ICINGA_CERT_SERVICE_BA_USER=admin
    - ICINGA_CERT_SERVICE_BA_PASSWORD=admin
    - ICINGA_CERT_SERVICE_API_USER=root
    - ICINGA_CERT_SERVICE_API_PASSWORD=icinga
    - ICINGA_CERT_SERVICE_SERVER=icinga2-master
    - ICINGA_CERT_SERVICE_PORT=4567
    - ICINGA_CERT_SERVICE_PATH=/
  volumes:
    - /tmp/docker-data/smashing-icinga2:/srv
  links:
    - icinga2-master:icinga2-master.matrix.lan
